[package]
name = "mxbo-web-preview"
version = "0.18.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mxbo-hud = { path = "../overlay/hud" }
mxbo-review = { path = "../review", default-features = false }
mxbo-motos-ui = { path = "../motos-ui" }
tiny-skia = "0.11"
wasm-bindgen = "=0.2.127"
